# Code Book

###Summary
"subject" is the ID of the test subject
"activity" is the type of activity 
nrow = 180
ncol = 68
```{r}
str(total_mean)

Classes ¡®data.table¡¯ and 'data.frame':	180 obs. of  68 variables:
 $ subject                    : int  1 1 1 1 1 1 3 3 3 3 ...
 $ activityLabels             : Factor w/ 6 levels "WALKING","WALKING_UPSTAIRS",..: 5 4 6 1 3 2 5 4 6 1 ...
 $ tBodyAcc-mean()-X          : num  0.279 0.261 0.222 0.277 0.289 ...
 $ tBodyAcc-mean()-Y          : num  -0.01614 -0.00131 -0.04051 -0.01738 -0.00992 ...
 $ tBodyAcc-mean()-Z          : num  -0.111 -0.105 -0.113 -0.111 -0.108 ...
 $ tBodyAcc-std()-X           : num  -0.996 -0.977 -0.928 -0.284 0.03 ...
 $ tBodyAcc-std()-Y           : num  -0.9732 -0.9226 -0.8368 0.1145 -0.0319 ...
 $ tBodyAcc-std()-Z           : num  -0.98 -0.94 -0.826 -0.26 -0.23 ...
 $ tGravityAcc-mean()-X       : num  0.943 0.832 -0.249 0.935 0.932 ...
 $ tGravityAcc-mean()-Y       : num  -0.273 0.204 0.706 -0.282 -0.267 ...
```


###The tidydataset contains 6 kinds of activity labels
1. WALKING
2. WALKING_UPSTAIRS
3. WALKING_DOWNSTAIRS
4. SITTING
5. STANDING
6. LAYING

### The tidydataset contains 66 variables 

1. "tBodyAcc-mean()-X"          
2. "tBodyAcc-mean()-Y"
3. "tBodyAcc-mean()-Z"
4. "tBodyAcc-std()-X"           
5. "tBodyAcc-std()-Y" 
6. "tBodyAcc-std()-Z"
7. "tGravityAcc-mean()-X"
8. "tGravityAcc-mean()-Y"
9. "tGravityAcc-mean()-Z"
10. "tGravityAcc-std()-X"        
11. "tGravityAcc-std()-Y"
12. "tGravityAcc-std()-Z"
13. "tBodyAccJerk-mean()-X"      
14. "tBodyAccJerk-mean()-Y"
15. "tBodyAccJerk-mean()-Z"
16. "tBodyAccJerk-std()-X"       
17. "tBodyAccJerk-std()-Y"
18. "tBodyAccJerk-std()-Z"
19. "tBodyGyro-mean()-X"         
20. "tBodyGyro-mean()-Y"
21. "tBodyGyro-mean()-Z"
22. "tBodyGyro-std()-X"          
23. "tBodyGyro-std()-Y" 
24. "tBodyGyro-std()-Z" 
25. "tBodyGyroJerk-mean()-X"     
26. "tBodyGyroJerk-mean()-Y"
27. "tBodyGyroJerk-mean()-Z"
28. "tBodyGyroJerk-std()-X"      
29. "tBodyGyroJerk-std()-Y"
30. "tBodyGyroJerk-std()-Z"
31. "tBodyAccMag-mean()"         
32. "tBodyAccMag-std()"
33. "tGravityAccMag-mean()"
34. "tGravityAccMag-std()"       
35. "tBodyAccJerkMag-mean()"
36. "tBodyAccJerkMag-std()"
37. "tBodyGyroMag-mean()"        
38. "tBodyGyroMag-std()"
39. "tBodyGyroJerkMag-mean()"
40. "tBodyGyroJerkMag-std()"     
41. "fBodyAcc-mean()-X"
42. "fBodyAcc-mean()-Y"
43. "fBodyAcc-mean()-Z"          
44. "fBodyAcc-std()-X"
45. "fBodyAcc-std()-Y"
46. "fBodyAcc-std()-Z"           
47. "fBodyAccJerk-mean()-X"
48. "fBodyAccJerk-mean()-Y"
49. "fBodyAccJerk-mean()-Z"      
50. "fBodyAccJerk-std()-X"
51. "fBodyAccJerk-std()-Y"
52. "fBodyAccJerk-std()-Z"       
53. "fBodyGyro-mean()-X"  
54. "fBodyGyro-mean()-Y"
55. "fBodyGyro-mean()-Z"         
56. "fBodyGyro-std()-X"
57. "fBodyGyro-std()-Y"   
58. "fBodyGyro-std()-Z"          
59. "fBodyAccMag-mean()"
60. "fBodyAccMag-std()"   
61. "fBodyBodyAccJerkMag-mean()" 
62. "fBodyBodyAccJerkMag-std()"
63. "fBodyBodyGyroMag-mean()" 
64. "fBodyBodyGyroMag-std()"     
65. "fBodyBodyGyroJerkMag-mean()" 
66. "fBodyBodyGyroJerkMag-std()"


